#!/bin/bash

while $(true); do
    if [ "$(git diff OWER.dot)" != "" ]; then
        dot -Tsvg OWER.dot -o live.svg
        git add live.svg
        git add OWER.dot
        git push origin HEAD:refs/heads/live
    fi
done
