#!/bin/bash

git push -f origin HEAD:refs/heads/live

while $(true); do
    if [ "$(git diff OWER.dot)" != "" ]; then
        gvpr -f reduce.g OWER.dot | \
        dot -Tsvg -o live.svg
        git add live.svg
        git add OWER.dot
        git commit -m "update"
        git push -f origin HEAD:refs/heads/live
    fi
done
